### ISSUE TITLE
Illegal tmin makes Beebrain barf

### ISSUE THREAD

**Issue by dreeves** [beeminder/road#201]
## Reseminata

1. Set tmin to tomorrow (1 day after asof) as in privatesuite/badtmin.bb

## Expectata

An error, or just do it even though there's no datapoints to show.

## Resultata

```
{
"inpath":"/Users/dreeves/prj/privatesuite/data/",
"outpath":"/Users/dreeves/prj/privatesuite/data/",
"slug":"badtmin",
"host":"dreevlaptop.local",
"process":1,
"request":1923,
"log":"badtmin @ 2021-03-16 17:20:13\n(1:1923)  Page creation (badtmin): 495.159ms\n(1:1923)  PAGE LOG: TypeError: Cannot read property '0' of undefined\n(1:1923)     at Object.self.gapFill (file:///Users/dreeves/prj/road/src/broad.js:890:19)\n(1:1923)     at beebrain.reloadRoad (file:///Users/dreeves/prj/road/src/beebrain.js:1267:22)\n(1:1923)     at genStats (file:///Users/dreeves/prj/road/src/beebrain.js:1324:43)\n(1:1923)     at new beebrain (file:///Users/dreeves/prj/road/src/beebrain.js:1361:1)\n(1:1923)     at loadGoal (file:///Users/dreeves/prj/road/src/bgraph.js:2136:9)\n(1:1923)     at loadGoalFromURL (file:///Users/dreeves/prj/road/src/bgraph.js:2229:5)\n(1:1923)     at async bgraph.loadGoal (file:///Users/dreeves/prj/road/src/bgraph.js:5480:3)\n(1:1923)     at async process (file:///Users/dreeves/prj/road/jsbrain_server/generate.html?bb=file://%2FUsers%2Fdreeves%2Fprj%2Fprivatesuite%2Fdata%2F/badtmin.bb&NOGRAPH=false:76:9)\n(1:1923)  Page render (badtmin): 70.033ms\n(1:1923)  renderer.js ERROR: Could not extract JSON from page!\n","error":"Processing error: Could not extract JSON from page!"
}
```

**Comment by dreeves** [comment]
I added an error-check for this:

> You can't set the graph bounds to be solely in the future!

**Comment by dreeves** [comment]
http://beeminder.com/changelog#3687
