### ISSUE TITLE
can't run gulp

### ISSUE THREAD

**Issue by adamwolf** [beeminder/road#291]
After following the instructions in the README with node 14.19.1, I get the following error when running `gulp`:

```
ReferenceError: primordials is not defined
    at fs.js:40:5
    at req_ (/Users/wolf/work/beeminder/road/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/Users/wolf/work/beeminder/road/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/Users/wolf/work/beeminder/road/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
```

**Comment by saranli** [comment]
Could this be related to a local issue? I was able to run gulp with the existing gulpfile with the following versions:

$ node -v
v16.13.0
$ npm -v
8.1.0
$ gulp -v
CLI version: 2.3.0
Local version: 4.0.2

gulp seems to compile the existing gulpfile in my system even when I use the v4 gulp that is installed locally.

Is there any reason why node could not be upgraded? Just trying to understand the issue so we can decide on how to proceed.

**Comment by adamwolf** [comment]
thanks @narthur!
