### ISSUE TITLE
Help debugging websocket issue?

### ISSUE THREAD

**Issue by adamwolf** [beeminder/road#85]
Hi folks! I run jsbrain locally, and I've always had this problem.

It runs fine for a while, and then:

```
(1:110) Request url=/?inpath=%2FUsers%2Fwolf%2Flocalprojects%2Fbeeminder%2Fbeebrain%2Fjsnonce&outpath=%2FUsers%2Fwolf%2Flocalprojects%2Fbeeminder%2Fbeebrain%2Fjsnonce&slug=6723a329-2a97-42ef-b78d-a81cbbcd21f4
Error: WebSocket is not open: readyState 3 (CLOSED)
    at WebSocket.send (/Users/wolf/localprojects/road/jsbrain_server/node_modules/ws/lib/websocket.js:329:19)
    at WebSocketTransport.send (/Users/wolf/localprojects/road/jsbrain_server/node_modules/puppeteer/lib/WebSocketTransport.js:60:14)
    at Connection._rawSend (/Users/wolf/localprojects/road/jsbrain_server/node_modules/puppeteer/lib/Connection.js:86:21)
    at Connection.send (/Users/wolf/localprojects/road/jsbrain_server/node_modules/puppeteer/lib/Connection.js:72:21)
    at Browser._createPageInContext (/Users/wolf/localprojects/road/jsbrain_server/node_modules/puppeteer/lib/Browser.js:174:47)
    at BrowserContext.newPage (/Users/wolf/localprojects/road/jsbrain_server/node_modules/puppeteer/lib/Browser.js:367:26)
    at Browser.newPage (/Users/wolf/localprojects/road/jsbrain_server/node_modules/puppeteer/lib/Browser.js:166:33)
    at Browser.<anonymous> (/Users/wolf/localprojects/road/jsbrain_server/node_modules/puppeteer/lib/helper.js:112:23)
    at Renderer.createPage (/Users/wolf/localprojects/road/jsbrain_server/renderer.js:43:37)
    at Renderer.render (/Users/wolf/localprojects/road/jsbrain_server/renderer.js:127:31)
  -- ASYNC --
    at Browser.<anonymous> (/Users/wolf/localprojects/road/jsbrain_server/node_modules/puppeteer/lib/helper.js:111:15)
    at Renderer.createPage (/Users/wolf/localprojects/road/jsbrain_server/renderer.js:43:37)
    at Renderer.render (/Users/wolf/localprojects/road/jsbrain_server/renderer.js:127:31)
    at app.use (/Users/wolf/localprojects/road/jsbrain_server/jsbrain_server.js:122:30)
    at Layer.handle [as handle_request] (/Users/wolf/localprojects/road/jsbrain_server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/wolf/localprojects/road/jsbrain_server/node_modules/express/lib/router/index.js:317:13)
    at /Users/wolf/localprojects/road/jsbrain_server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/wolf/localprojects/road/jsbrain_server/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/wolf/localprojects/road/jsbrain_server/node_modules/express/lib/router/index.js:275:10)
    at expressInit (/Users/wolf/localprojects/road/jsbrain_server/node_modules/express/lib/middleware/init.js:40:5)
(node:52761) UnhandledPromiseRejectionWarning: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:482:11)
    at ServerResponse.header (/Users/wolf/localprojects/road/jsbrain_server/node_modules/express/lib/response.js:771:10)
    at ServerResponse.send (/Users/wolf/localprojects/road/jsbrain_server/node_modules/express/lib/response.js:170:12)
    at app.use (/Users/wolf/localprojects/road/jsbrain_server/jsbrain_server.js:177:28)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
(node:52761) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:52761) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

After that happens once, I have to kill it and restart it for it to work again.  I'm not sure if it's the same job that does it, or not.  How would I start debugging this?

**Comment by adamwolf** [comment]
server is at npm version 6.4.1, i'm at 6.11.3, and @bsoule is at 6.9.0.
