### ISSUE TITLE
unhandled promise rejection in dev env

### ISSUE THREAD

**Issue by bsoule** [beeminder/road#99]
I've seen this happen twice in the past week when I'm running tests in my dev environment. It seems to crash/lock up my jsbrain server, so that's a bit worrisome if it's not recovering on its own. [It could cause havoc in production if it happened there... I'll add a gissue over there for handling jsbrain errors better].

```
(1:368) renderer.js: Creating new page in slot 5
Error: WebSocket is not open: readyState 3 (CLOSED)
    at WebSocket.send (/Users/bsoule/factory/roadjs/jsbrain_server/node_modules/ws/lib/websocket.js:329:19)
    at WebSocketTransport.send (/Users/bsoule/factory/roadjs/jsbrain_server/node_modules/puppeteer/lib/WebSocketTransport.js:60:14)
    at Connection._rawSend (/Users/bsoule/factory/roadjs/jsbrain_server/node_modules/puppeteer/lib/Connection.js:86:21)
    at Connection.send (/Users/bsoule/factory/roadjs/jsbrain_server/node_modules/puppeteer/lib/Connection.js:72:21)
    at Browser._createPageInContext (/Users/bsoule/factory/roadjs/jsbrain_server/node_modules/puppeteer/lib/Browser.js:174:47)
    at BrowserContext.newPage (/Users/bsoule/factory/roadjs/jsbrain_server/node_modules/puppeteer/lib/Browser.js:367:26)
    at Browser.newPage (/Users/bsoule/factory/roadjs/jsbrain_server/node_modules/puppeteer/lib/Browser.js:166:33)
    at Browser.<anonymous> (/Users/bsoule/factory/roadjs/jsbrain_server/node_modules/puppeteer/lib/helper.js:112:23)
    at Renderer.renderPage (/Users/bsoule/factory/roadjs/jsbrain_server/renderer.js:64:33)
    at Renderer.render (/Users/bsoule/factory/roadjs/jsbrain_server/renderer.js:165:29)
  -- ASYNC --
    at Browser.<anonymous> (/Users/bsoule/factory/roadjs/jsbrain_server/node_modules/puppeteer/lib/helper.js:111:15)
    at Renderer.renderPage (/Users/bsoule/factory/roadjs/jsbrain_server/renderer.js:64:33)
    at Renderer.render (/Users/bsoule/factory/roadjs/jsbrain_server/renderer.js:165:29)
    at /Users/bsoule/factory/roadjs/jsbrain_server/jsbrain_server.js:122:30
    at Layer.handle [as handle_request] (/Users/bsoule/factory/roadjs/jsbrain_server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/bsoule/factory/roadjs/jsbrain_server/node_modules/express/lib/router/index.js:317:13)
    at /Users/bsoule/factory/roadjs/jsbrain_server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/bsoule/factory/roadjs/jsbrain_server/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/bsoule/factory/roadjs/jsbrain_server/node_modules/express/lib/router/index.js:275:10)
    at expressInit (/Users/bsoule/factory/roadjs/jsbrain_server/node_modules/express/lib/middleware/init.js:40:5)
(node:5323) UnhandledPromiseRejectionWarning: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:485:11)
    at ServerResponse.header (/Users/bsoule/factory/roadjs/jsbrain_server/node_modules/express/lib/response.js:771:10)
    at ServerResponse.send (/Users/bsoule/factory/roadjs/jsbrain_server/node_modules/express/lib/response.js:170:12)
    at /Users/bsoule/factory/roadjs/jsbrain_server/jsbrain_server.js:177:28
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
(node:5323) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 78)
(1:369) ============================================
(1:369) Request url=/?inpath=%2FUsers%2Fbsoule%2Ffactory%2Fbeeminder%2Fbeebrain%2Fjsnonce&outpath=%2FUsers%2Fbsoule%2Ffactory%2Fbeeminder%2Fbeebrain%2Fjsnonce&slug=3bf4ba7b-56b4-4e22-8cf3-d4e6e5d2e7df
(1:369) renderer.js: Creating new page in slot 5
Error: WebSocket is not open: readyState 3 (CLOSED)
    at WebSocket.send (/Users/bsoule/factory/roadjs/jsbrain_server/node_modules/ws/lib/websocket.js:329:19)
    at WebSocketTransport.send (/Users/bsoule/factory/roadjs/jsbrain_server/node_modules/puppeteer/lib/WebSocketTransport.js:60:14)
    at Connection._rawSend (/Users/bsoule/factory/roadjs/jsbrain_server/node_modules/puppeteer/lib/Connection.js:86:21)
    at Connection.send (/Users/bsoule/factory/roadjs/jsbrain_server/node_modules/puppeteer/lib/Connection.js:72:21)
    at Browser._createPageInContext (/Users/bsoule/factory/roadjs/jsbrain_server/node_modules/puppeteer/lib/Browser.js:174:47)
    at BrowserContext.newPage (/Users/bsoule/factory/roadjs/jsbrain_server/node_modules/puppeteer/lib/Browser.js:367:26)
    at Browser.newPage (/Users/bsoule/factory/roadjs/jsbrain_server/node_modules/puppeteer/lib/Browser.js:166:33)
    at Browser.<anonymous> (/Users/bsoule/factory/roadjs/jsbrain_server/node_modules/puppeteer/lib/helper.js:112:23)
    at Renderer.renderPage (/Users/bsoule/factory/roadjs/jsbrain_server/renderer.js:64:33)
    at Renderer.render (/Users/bsoule/factory/roadjs/jsbrain_server/renderer.js:165:29)
  -- ASYNC --
    at Browser.<anonymous> (/Users/bsoule/factory/roadjs/jsbrain_server/node_modules/puppeteer/lib/helper.js:111:15)
    at Renderer.renderPage (/Users/bsoule/factory/roadjs/jsbrain_server/renderer.js:64:33)
    at Renderer.render (/Users/bsoule/factory/roadjs/jsbrain_server/renderer.js:165:29)
    at /Users/bsoule/factory/roadjs/jsbrain_server/jsbrain_server.js:122:30
    at Layer.handle [as handle_request] (/Users/bsoule/factory/roadjs/jsbrain_server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/bsoule/factory/roadjs/jsbrain_server/node_modules/express/lib/router/index.js:317:13)
    at /Users/bsoule/factory/roadjs/jsbrain_server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/bsoule/factory/roadjs/jsbrain_server/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/bsoule/factory/roadjs/jsbrain_server/node_modules/express/lib/router/index.js:275:10)
    at expressInit (/Users/bsoule/factory/roadjs/jsbrain_server/node_modules/express/lib/middleware/init.js:40:5)
(node:5323) UnhandledPromiseRejectionWarning: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:485:11)
    at ServerResponse.header (/Users/bsoule/factory/roadjs/jsbrain_server/node_modules/express/lib/response.js:771:10)
    at ServerResponse.send (/Users/bsoule/factory/roadjs/jsbrain_server/node_modules/express/lib/response.js:170:12)
    at /Users/bsoule/factory/roadjs/jsbrain_server/jsbrain_server.js:177:28
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
(node:5323) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 80)
```

**Comment by bsoule** [comment]
This causes the following unrecoverable error in automon:

```
roadjs/automon % ./automon.py /Users/bsoule/factory/privatesuite/data ~/factory/roadjs/src
_addstr error: ww:80,wh:46,y:32, x:1,str=2.000000000000006, 2]]
_addstr error: ww:80,wh:46,y:33, x:1,str=* tluz= 20220929
_addstr error: ww:80,wh:46,y:34, x:1,str=* tcur= 20191124
_addstr error: ww:80,wh:46,y:35, x:1,str=* vcur= 12
_addstr error: ww:80,wh:46,y:36, x:1,str=* vprev= 12
_addstr error: ww:80,wh:46,y:37, x:1,str=* rcur= 2
_addstr error: ww:80,wh:46,y:38, x:1,str=* ravg= 2.060588065429615
_addstr error: ww:80,wh:46,y:39, x:1,str=* tdat= 20170221
_addstr error: ww:80,wh:46,y:2, x:65,str= Last: 1392ms
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "./automon.py", line 666, in worker
    retval = jsbrain_make(job)
  File "./automon.py", line 515, in jsbrain_make
    rj = resp.json()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by adamwolf** [comment]
Something like this happens to me daily.  I thought it was my dev env.

**Comment by bsoule** [comment]
oh yeah, it's happening to me multiple times a day now. what version of node do you have locally? mine is 12.x all three servers are running 10.x

I think I'm gonna try downgrading node. also we likely need to note somehow to resolve this before we upgrade node on servers, or we will have a nasty surprise if we forget about this.

**Comment by adamwolf** [comment]
see #85 
I'm on 13.8 for node.  If we can recreate it reliably I can easily test across a spread of node versions, but it'll take a while if the test is "run in adam's dev env for half a day" :)

**Comment by bsoule** [comment]
I tried downgrading back to node 10, but still seeing the issue.
